version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'
    volumes:
      - ./init-schema.sql:/docker-entrypoint-initdb.d/01_init_schema.sql
      - ./init-data.sql:/docker-entrypoint-initdb.d/02_init_data.sql
    networks:
      - backend-network
networks:
  backend-network: